# Generated by Django 6.1.1 on 2026-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_DB',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('Rc_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DL_Number', models.CharField(max_length=16)),
                ('Vehicle_model', models.CharField(max_length=10)),
                ('Issues', models.TextField()),
            ],
        ),
    ]
